<?php

namespace AppBundle\Repository\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealRepository extends EntityRepository
{
    public function getQueryHome()
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT m
                FROM AppBundle:Meal p
                WHERE m.meal_date <= :dateend
                and m.meal_date >= :datestart
                and m.user = :user
                
                ORDER BY p.meal_date DESC
            ')
            ->setParameter('now', new \DateTime())
            ;
    }
}
